### ISSUE TITLE
关联是指进展和任务关联，进展是指一次commit，一次issue或一次pr

### ISSUE THREAD

**Issue by TrickEye** [buaa2023sw/doc#3]
（最后一个表得改改）

**Comment by Guo-HY** [comment]
https://github.com/buaa2023sw/doc/commit/81af7147a2bddd2de62d3c7661c28111a9efb4d7

看一看是否可以？

**Comment by TrickEye** [comment]
~~可以，但是没有在数据库表中体现）~~

我是傻逼看错文件了

**Comment by TrickEye** [comment]
resolved
